### ISSUE TITLE
几个问题及解决问题

### ISSUE THREAD

**Issue by zhjurz** [MuCqq/dujiaoka-mcq#5]
1.官方模板unicorn的logo部分有问题，css亮度设置为0，导致无法正常显示。应在/public/assets/unicorn/css中96行改0为1
2.官方文档之中没要求在宝塔中删除syslink禁用函数导致创建链接的时候出现问题  应在宝塔的php设置中把syslink给解禁

这是我在搭建时发现的问题，新手勿喷！

**Comment by luwuchencao** [comment]
为什么我搭建几次都失败，这个搭建需要原版本吗？意思就是把改版的覆盖到原版本在搭建？

**Comment by ZyphrZero** [comment]
已修改
