### ISSUE TITLE
请教 搭建问题

### ISSUE THREAD

**Issue by luwuchencao** [MuCqq/dujiaoka-mcq#6]
这个是覆盖原版本搭建，还是直接用这个版本搭建！尝试几次失败，原版本搭建很简单

**Comment by ZyphrZero** [comment]
全部重新搭建

**Comment by luwuchencao** [comment]
> 全部重新搭建

只上传本程序代码吗？原版不需要上传吧，搭建了几次都失败了

**Comment by ZyphrZero** [comment]
不需要，使用当前仓库代码
https://github.com/MuCqq/dujiaoka-mcq/wiki/install

**Comment by luwuchencao** [comment]
> 不需要，使用当前仓库代码 https://github.com/MuCqq/dujiaoka-mcq/wiki/install

谢谢，env文件只修改网站，和数据库就可以了吧
